version: '2.1'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:6.1.1
    ports:
      - "22181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  zookeeper-2:
    image: confluentinc/cp-zookeeper:6.1.1
    ports:
      - "32181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-1:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - '19092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-1:2181,zookeeper-2:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_MIN_INSYNC_REPLICAS: '1'

  kafka-2:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - '19093:9092'
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-1:2181,zookeeper-2:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9093,PLAINTEXT_HOST://localhost:19093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_MIN_INSYNC_REPLICAS: '1'

  kafka-3:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - '19094:9092'
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-1:2181,zookeeper-2:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9094,PLAINTEXT_HOST://localhost:19094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_MIN_INSYNC_REPLICAS: '1'

  init-kafka:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka-1:9092,kafka-2:9093,kafka-3:9094 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka-1:9092,kafka-2:9093,kafka-3:9094 --create --if-not-exists --topic github-events --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka-1:9092,kafka-2:9093,kafka-3:9094 --list
      "

  postgres:
    image: "postgres:11.22-bullseye"
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

  apiServer:
    image: omribar/github-event-handler:1.0.0
    depends_on:
      postgres:
        condition: service_started
    ports:
      - '3000:3000'
    command:
      - /bin/sh
      - -c
      - go run apiServer/main.go
    environment:
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=secret

  eventProcessor:
    image: omribar/github-event-handler:1.0.0
    depends_on:
      init-kafka:
        condition: service_completed_successfully
      postgres:
        condition: service_started
    command:
      - /bin/sh
      - -c
      - go run eventProcessor/main.go
    environment:
      - KAFKA_BROKER=kafka-1:9092,kafka-2:9093,kafka-3:9094
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=secret

  eventSampler:
    image: omribar/github-event-handler:1.0.0
    depends_on:
      init-kafka:
        condition: service_completed_successfully
    command:
      - /bin/sh
      - -c
      - go run eventSampler/main.go
    environment:
      - KAFKA_BROKER=kafka-1:9092
      - GITHUB_TOKEN=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

volumes:
  postgres_data: